// src/pages/home.vue
<script setup lang="ts">
import { useCountStore } from '@/stores/modules/useCount'

const countStort = useCountStore();
const { count, doubleCount } = storeToRefs(countStort);
const { increment } = countStort;
</script>

<template>
  <div class="flex flex-col gap-2 items-center justify-center w-full">
		<div class="text-[32px] text-slate-200">{{ count }}</div>
		<div class="text-[32px] text-slate-200">{{ doubleCount }}</div>
		<button class="w-[128px] p-2 bg-white border-2 border-dashed border-red-500" @click="increment">+++</button>
	</div>
</template>

// vitest-playwright-monorepo/src/pages/home/index.tsx
import { useAppSelector } from '@/stores';
import { Button } from 'antd';
const Home = () => {
	const navigate = useNavigate();

	const count = useAppSelector((state) => state.counter.count);

	const backHome = () => {
		navigate('/about');
	};

	return (
		<div className="page-container flex flex-col gap-3 items-center justify-center w-full h-full">
			<h1 className='title'>首页</h1>
			<div>当前count的值{count}</div>
			<div>
				<Button onClick={backHome}>about页面</Button>
			</div>
		</div>
	);
};

export default Home;
